# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  
  config.vm.network "private_network", type: "dhcp"

  config.vm.define "linux-1" do |subconfig|
    subconfig.vm.box = 'centos/7'
    subconfig.ssh.forward_agent = true
  end
  
  config.vm.define "linux-2" do |subconfig|
    subconfig.vm.box = 'centos/7'
    subconfig.ssh.forward_agent = true
  end
  
  config.vm.define "win-1" do |subconfig|
    subconfig.vm.box = "mrlesmithjr/windows2016"
    subconfig.vm.guest = :windows
    subconfig.vm.communicator = "winrm"
  end

  config.vm.define "win-2" do |subconfig|
    subconfig.vm.box = "mrlesmithjr/windows2016"
    subconfig.vm.guest = :windows
    subconfig.vm.communicator = "winrm"
  end
 
end
